### ISSUE TITLE
Release crash on start

### ISSUE THREAD

**Issue by newemka** [aiekick/SdfFontDesigner#37]
Hello, 
When I run the app, the debug window appears, then the app window, then everything disappears.  
Same behavior for X64 and x86 releases. 
I'm on Window 10 Pro Version 22H2

**Comment by aiekick** [comment]
Hello,
do you have something in the file "debug.log" ?

maye be you need to install the redistribuable 2015 : 
https://www.microsoft.com/fr-fr/download/details.aspx?id=53840

**Comment by newemka** [comment]
vc_redist.x64 is already installed, the debug.log file is empty.

**Comment by aiekick** [comment]
ok.. sorry no ideas.

**Comment by newemka** [comment]
no worries :)

**Comment by aiekick** [comment]
btw i will open the code in few month. maybe by compiling you will see the issue

**Comment by newemka** [comment]
I was looking for an easy way to create msdf fonts in order to use them with Tooll3 [https://github.com/tooll3/t3/wiki/AddingFonts](https://github.com/tooll3/t3/wiki/AddingFonts)

**Comment by newemka** [comment]
in the end i made a UI in an electron app https://github.com/newemka/MSDFtron
